modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
logoFile = "pack.png"
[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    updateJSONURL = "https://update.mc.vanilla.xin/${mod_id}/${loader_type}/${minecraft_version}"
    displayURL = "https://mc.vanilla.xin/${mod_id}"
    authors = "${mod_authors}"
    description = '''${mod_description}'''
    clientRequired = false
[[dependencies."${mod_id}"]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "${mod_id}"
    mandatory = true
    versionRange = "[1.0.0,)"
    ordering = "NONE"
    side = "SERVER"
[[dependencies."${mod_id}"]]
    modId = "${mod_id}"
    mandatory = false
    versionRange = "[1.0.0,)"
    ordering = "NONE"
    side = "CLIENT"
